// Code generated by protoc-gen-go. DO NOT EDIT.
// source: water.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperateResult int32

const (
	OperateResult_OK    OperateResult = 0
	OperateResult_Fault OperateResult = 1
)

var OperateResult_name = map[int32]string{
	0: "OK",
	1: "Fault",
}

var OperateResult_value = map[string]int32{
	"OK":    0,
	"Fault": 1,
}

func (x OperateResult) String() string {
	return proto.EnumName(OperateResult_name, int32(x))
}

func (OperateResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DeviceInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{1}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceInfo) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DeviceCountConditional struct {
	DeviceType           string   `protobuf:"bytes,1,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Building             string   `protobuf:"bytes,2,opt,name=Building,proto3" json:"Building,omitempty"`
	Floor                string   `protobuf:"bytes,3,opt,name=Floor,proto3" json:"Floor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceCountConditional) Reset()         { *m = DeviceCountConditional{} }
func (m *DeviceCountConditional) String() string { return proto.CompactTextString(m) }
func (*DeviceCountConditional) ProtoMessage()    {}
func (*DeviceCountConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{2}
}

func (m *DeviceCountConditional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCountConditional.Unmarshal(m, b)
}
func (m *DeviceCountConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCountConditional.Marshal(b, m, deterministic)
}
func (m *DeviceCountConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCountConditional.Merge(m, src)
}
func (m *DeviceCountConditional) XXX_Size() int {
	return xxx_messageInfo_DeviceCountConditional.Size(m)
}
func (m *DeviceCountConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCountConditional.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCountConditional proto.InternalMessageInfo

func (m *DeviceCountConditional) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceCountConditional) GetBuilding() string {
	if m != nil {
		return m.Building
	}
	return ""
}

func (m *DeviceCountConditional) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

type DeviceCountResponse struct {
	Result               OperateResult `protobuf:"varint,1,opt,name=Result,proto3,enum=main.OperateResult" json:"Result,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	DeviceType           string        `protobuf:"bytes,3,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Building             string        `protobuf:"bytes,4,opt,name=Building,proto3" json:"Building,omitempty"`
	Floor                string        `protobuf:"bytes,5,opt,name=Floor,proto3" json:"Floor,omitempty"`
	Data                 []*DeviceInfo `protobuf:"bytes,6,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceCountResponse) Reset()         { *m = DeviceCountResponse{} }
func (m *DeviceCountResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceCountResponse) ProtoMessage()    {}
func (*DeviceCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{3}
}

func (m *DeviceCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCountResponse.Unmarshal(m, b)
}
func (m *DeviceCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCountResponse.Marshal(b, m, deterministic)
}
func (m *DeviceCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCountResponse.Merge(m, src)
}
func (m *DeviceCountResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceCountResponse.Size(m)
}
func (m *DeviceCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCountResponse proto.InternalMessageInfo

func (m *DeviceCountResponse) GetResult() OperateResult {
	if m != nil {
		return m.Result
	}
	return OperateResult_OK
}

func (m *DeviceCountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DeviceCountResponse) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceCountResponse) GetBuilding() string {
	if m != nil {
		return m.Building
	}
	return ""
}

func (m *DeviceCountResponse) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

func (m *DeviceCountResponse) GetData() []*DeviceInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeviceCountsConditional struct {
	Conditionals         []*DeviceCountConditional `protobuf:"bytes,1,rep,name=Conditionals,proto3" json:"Conditionals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DeviceCountsConditional) Reset()         { *m = DeviceCountsConditional{} }
func (m *DeviceCountsConditional) String() string { return proto.CompactTextString(m) }
func (*DeviceCountsConditional) ProtoMessage()    {}
func (*DeviceCountsConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{4}
}

func (m *DeviceCountsConditional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCountsConditional.Unmarshal(m, b)
}
func (m *DeviceCountsConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCountsConditional.Marshal(b, m, deterministic)
}
func (m *DeviceCountsConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCountsConditional.Merge(m, src)
}
func (m *DeviceCountsConditional) XXX_Size() int {
	return xxx_messageInfo_DeviceCountsConditional.Size(m)
}
func (m *DeviceCountsConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCountsConditional.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCountsConditional proto.InternalMessageInfo

func (m *DeviceCountsConditional) GetConditionals() []*DeviceCountConditional {
	if m != nil {
		return m.Conditionals
	}
	return nil
}

type DeviceCountsResponse struct {
	Datas                []*DeviceCountResponse `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeviceCountsResponse) Reset()         { *m = DeviceCountsResponse{} }
func (m *DeviceCountsResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceCountsResponse) ProtoMessage()    {}
func (*DeviceCountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{5}
}

func (m *DeviceCountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCountsResponse.Unmarshal(m, b)
}
func (m *DeviceCountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCountsResponse.Marshal(b, m, deterministic)
}
func (m *DeviceCountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCountsResponse.Merge(m, src)
}
func (m *DeviceCountsResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceCountsResponse.Size(m)
}
func (m *DeviceCountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCountsResponse proto.InternalMessageInfo

func (m *DeviceCountsResponse) GetDatas() []*DeviceCountResponse {
	if m != nil {
		return m.Datas
	}
	return nil
}

type DeviceValueConditional struct {
	Building             string   `protobuf:"bytes,1,opt,name=Building,proto3" json:"Building,omitempty"`
	Floor                string   `protobuf:"bytes,2,opt,name=Floor,proto3" json:"Floor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceValueConditional) Reset()         { *m = DeviceValueConditional{} }
func (m *DeviceValueConditional) String() string { return proto.CompactTextString(m) }
func (*DeviceValueConditional) ProtoMessage()    {}
func (*DeviceValueConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{6}
}

func (m *DeviceValueConditional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceValueConditional.Unmarshal(m, b)
}
func (m *DeviceValueConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceValueConditional.Marshal(b, m, deterministic)
}
func (m *DeviceValueConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceValueConditional.Merge(m, src)
}
func (m *DeviceValueConditional) XXX_Size() int {
	return xxx_messageInfo_DeviceValueConditional.Size(m)
}
func (m *DeviceValueConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceValueConditional.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceValueConditional proto.InternalMessageInfo

func (m *DeviceValueConditional) GetBuilding() string {
	if m != nil {
		return m.Building
	}
	return ""
}

func (m *DeviceValueConditional) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

type DeviceValueResponse struct {
	Result               OperateResult `protobuf:"varint,1,opt,name=Result,proto3,enum=main.OperateResult" json:"Result,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Building             string        `protobuf:"bytes,3,opt,name=Building,proto3" json:"Building,omitempty"`
	Floor                string        `protobuf:"bytes,4,opt,name=Floor,proto3" json:"Floor,omitempty"`
	Data                 []*DeviceInfo `protobuf:"bytes,5,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceValueResponse) Reset()         { *m = DeviceValueResponse{} }
func (m *DeviceValueResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceValueResponse) ProtoMessage()    {}
func (*DeviceValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{7}
}

func (m *DeviceValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceValueResponse.Unmarshal(m, b)
}
func (m *DeviceValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceValueResponse.Marshal(b, m, deterministic)
}
func (m *DeviceValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceValueResponse.Merge(m, src)
}
func (m *DeviceValueResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceValueResponse.Size(m)
}
func (m *DeviceValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceValueResponse proto.InternalMessageInfo

func (m *DeviceValueResponse) GetResult() OperateResult {
	if m != nil {
		return m.Result
	}
	return OperateResult_OK
}

func (m *DeviceValueResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DeviceValueResponse) GetBuilding() string {
	if m != nil {
		return m.Building
	}
	return ""
}

func (m *DeviceValueResponse) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

func (m *DeviceValueResponse) GetData() []*DeviceInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeviceValuesConditional struct {
	Conditionals         []*DeviceValueConditional `protobuf:"bytes,1,rep,name=Conditionals,proto3" json:"Conditionals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DeviceValuesConditional) Reset()         { *m = DeviceValuesConditional{} }
func (m *DeviceValuesConditional) String() string { return proto.CompactTextString(m) }
func (*DeviceValuesConditional) ProtoMessage()    {}
func (*DeviceValuesConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{8}
}

func (m *DeviceValuesConditional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceValuesConditional.Unmarshal(m, b)
}
func (m *DeviceValuesConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceValuesConditional.Marshal(b, m, deterministic)
}
func (m *DeviceValuesConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceValuesConditional.Merge(m, src)
}
func (m *DeviceValuesConditional) XXX_Size() int {
	return xxx_messageInfo_DeviceValuesConditional.Size(m)
}
func (m *DeviceValuesConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceValuesConditional.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceValuesConditional proto.InternalMessageInfo

func (m *DeviceValuesConditional) GetConditionals() []*DeviceValueConditional {
	if m != nil {
		return m.Conditionals
	}
	return nil
}

type DeviceValuesResponse struct {
	Datas                []*DeviceValueResponse `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeviceValuesResponse) Reset()         { *m = DeviceValuesResponse{} }
func (m *DeviceValuesResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceValuesResponse) ProtoMessage()    {}
func (*DeviceValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{9}
}

func (m *DeviceValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceValuesResponse.Unmarshal(m, b)
}
func (m *DeviceValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceValuesResponse.Marshal(b, m, deterministic)
}
func (m *DeviceValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceValuesResponse.Merge(m, src)
}
func (m *DeviceValuesResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceValuesResponse.Size(m)
}
func (m *DeviceValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceValuesResponse proto.InternalMessageInfo

func (m *DeviceValuesResponse) GetDatas() []*DeviceValueResponse {
	if m != nil {
		return m.Datas
	}
	return nil
}

type DeviceDetail struct {
	Max                  int32    `protobuf:"varint,1,opt,name=Max,proto3" json:"Max,omitempty"`
	Min                  int32    `protobuf:"varint,2,opt,name=Min,proto3" json:"Min,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Value                int32    `protobuf:"varint,4,opt,name=Value,proto3" json:"Value,omitempty"`
	DeviceType           string   `protobuf:"bytes,5,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDetail) Reset()         { *m = DeviceDetail{} }
func (m *DeviceDetail) String() string { return proto.CompactTextString(m) }
func (*DeviceDetail) ProtoMessage()    {}
func (*DeviceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{10}
}

func (m *DeviceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDetail.Unmarshal(m, b)
}
func (m *DeviceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDetail.Marshal(b, m, deterministic)
}
func (m *DeviceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDetail.Merge(m, src)
}
func (m *DeviceDetail) XXX_Size() int {
	return xxx_messageInfo_DeviceDetail.Size(m)
}
func (m *DeviceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDetail proto.InternalMessageInfo

func (m *DeviceDetail) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *DeviceDetail) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *DeviceDetail) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *DeviceDetail) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DeviceDetail) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

type DeviceDetailConditional struct {
	DeviceEUI            string   `protobuf:"bytes,1,opt,name=DeviceEUI,proto3" json:"DeviceEUI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDetailConditional) Reset()         { *m = DeviceDetailConditional{} }
func (m *DeviceDetailConditional) String() string { return proto.CompactTextString(m) }
func (*DeviceDetailConditional) ProtoMessage()    {}
func (*DeviceDetailConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{11}
}

func (m *DeviceDetailConditional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDetailConditional.Unmarshal(m, b)
}
func (m *DeviceDetailConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDetailConditional.Marshal(b, m, deterministic)
}
func (m *DeviceDetailConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDetailConditional.Merge(m, src)
}
func (m *DeviceDetailConditional) XXX_Size() int {
	return xxx_messageInfo_DeviceDetailConditional.Size(m)
}
func (m *DeviceDetailConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDetailConditional.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDetailConditional proto.InternalMessageInfo

func (m *DeviceDetailConditional) GetDeviceEUI() string {
	if m != nil {
		return m.DeviceEUI
	}
	return ""
}

type DeviceDetailResponse struct {
	Result               OperateResult   `protobuf:"varint,1,opt,name=Result,proto3,enum=main.OperateResult" json:"Result,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	DeviceEUI            string          `protobuf:"bytes,3,opt,name=DeviceEUI,proto3" json:"DeviceEUI,omitempty"`
	Data                 []*DeviceDetail `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeviceDetailResponse) Reset()         { *m = DeviceDetailResponse{} }
func (m *DeviceDetailResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceDetailResponse) ProtoMessage()    {}
func (*DeviceDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{12}
}

func (m *DeviceDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDetailResponse.Unmarshal(m, b)
}
func (m *DeviceDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDetailResponse.Marshal(b, m, deterministic)
}
func (m *DeviceDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDetailResponse.Merge(m, src)
}
func (m *DeviceDetailResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceDetailResponse.Size(m)
}
func (m *DeviceDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDetailResponse proto.InternalMessageInfo

func (m *DeviceDetailResponse) GetResult() OperateResult {
	if m != nil {
		return m.Result
	}
	return OperateResult_OK
}

func (m *DeviceDetailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DeviceDetailResponse) GetDeviceEUI() string {
	if m != nil {
		return m.DeviceEUI
	}
	return ""
}

func (m *DeviceDetailResponse) GetData() []*DeviceDetail {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeviceDetailsConditional struct {
	Conditionals         []*DeviceDetailConditional `protobuf:"bytes,1,rep,name=Conditionals,proto3" json:"Conditionals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeviceDetailsConditional) Reset()         { *m = DeviceDetailsConditional{} }
func (m *DeviceDetailsConditional) String() string { return proto.CompactTextString(m) }
func (*DeviceDetailsConditional) ProtoMessage()    {}
func (*DeviceDetailsConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{13}
}

func (m *DeviceDetailsConditional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDetailsConditional.Unmarshal(m, b)
}
func (m *DeviceDetailsConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDetailsConditional.Marshal(b, m, deterministic)
}
func (m *DeviceDetailsConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDetailsConditional.Merge(m, src)
}
func (m *DeviceDetailsConditional) XXX_Size() int {
	return xxx_messageInfo_DeviceDetailsConditional.Size(m)
}
func (m *DeviceDetailsConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDetailsConditional.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDetailsConditional proto.InternalMessageInfo

func (m *DeviceDetailsConditional) GetConditionals() []*DeviceDetailConditional {
	if m != nil {
		return m.Conditionals
	}
	return nil
}

type DeviceDetailsResponse struct {
	Datas                []*DeviceDetailResponse `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DeviceDetailsResponse) Reset()         { *m = DeviceDetailsResponse{} }
func (m *DeviceDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceDetailsResponse) ProtoMessage()    {}
func (*DeviceDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{14}
}

func (m *DeviceDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDetailsResponse.Unmarshal(m, b)
}
func (m *DeviceDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDetailsResponse.Marshal(b, m, deterministic)
}
func (m *DeviceDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDetailsResponse.Merge(m, src)
}
func (m *DeviceDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceDetailsResponse.Size(m)
}
func (m *DeviceDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDetailsResponse proto.InternalMessageInfo

func (m *DeviceDetailsResponse) GetDatas() []*DeviceDetailResponse {
	if m != nil {
		return m.Datas
	}
	return nil
}

func init() {
	proto.RegisterEnum("main.OperateResult", OperateResult_name, OperateResult_value)
	proto.RegisterType((*Empty)(nil), "main.Empty")
	proto.RegisterType((*DeviceInfo)(nil), "main.DeviceInfo")
	proto.RegisterType((*DeviceCountConditional)(nil), "main.DeviceCountConditional")
	proto.RegisterType((*DeviceCountResponse)(nil), "main.DeviceCountResponse")
	proto.RegisterType((*DeviceCountsConditional)(nil), "main.DeviceCountsConditional")
	proto.RegisterType((*DeviceCountsResponse)(nil), "main.DeviceCountsResponse")
	proto.RegisterType((*DeviceValueConditional)(nil), "main.DeviceValueConditional")
	proto.RegisterType((*DeviceValueResponse)(nil), "main.DeviceValueResponse")
	proto.RegisterType((*DeviceValuesConditional)(nil), "main.DeviceValuesConditional")
	proto.RegisterType((*DeviceValuesResponse)(nil), "main.DeviceValuesResponse")
	proto.RegisterType((*DeviceDetail)(nil), "main.DeviceDetail")
	proto.RegisterType((*DeviceDetailConditional)(nil), "main.DeviceDetailConditional")
	proto.RegisterType((*DeviceDetailResponse)(nil), "main.DeviceDetailResponse")
	proto.RegisterType((*DeviceDetailsConditional)(nil), "main.DeviceDetailsConditional")
	proto.RegisterType((*DeviceDetailsResponse)(nil), "main.DeviceDetailsResponse")
}

func init() { proto.RegisterFile("water.proto", fileDescriptor_c895fc20b6ed18c2) }

var fileDescriptor_c895fc20b6ed18c2 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x25, 0x4d, 0x52, 0xe8, 0xb7, 0x32, 0x2a, 0x6f, 0x40, 0x08, 0xdb, 0x54, 0x59, 0x08, 0x55,
	0x20, 0x15, 0x54, 0x24, 0xb8, 0x05, 0xd6, 0x6d, 0x2a, 0x7f, 0x95, 0x0c, 0x83, 0x0b, 0xc4, 0x85,
	0x61, 0x06, 0x05, 0xa5, 0x49, 0xd5, 0xb8, 0xc0, 0x24, 0xde, 0x84, 0x57, 0xe0, 0x51, 0x78, 0x07,
	0x5e, 0x05, 0xc5, 0x8e, 0xdb, 0xcf, 0x49, 0x53, 0x0d, 0x69, 0x77, 0xb6, 0x3f, 0xe7, 0x7c, 0xc7,
	0xe7, 0xf8, 0x38, 0xb0, 0xf1, 0x9d, 0x4b, 0x31, 0xeb, 0x4f, 0x67, 0xa9, 0x4c, 0x89, 0x37, 0xe1,
	0x51, 0x42, 0x2f, 0x82, 0x7f, 0x30, 0x99, 0xca, 0x53, 0xfa, 0x10, 0x60, 0x28, 0xbe, 0x45, 0x9f,
	0xc4, 0x28, 0xf9, 0x9c, 0x12, 0x02, 0xde, 0x2b, 0x3e, 0x11, 0x81, 0xd3, 0x75, 0x7a, 0x2d, 0xa6,
	0xc6, 0x64, 0x1b, 0xfc, 0xb7, 0x3c, 0x9e, 0x8b, 0xa0, 0xd1, 0x75, 0x7a, 0x3e, 0xd3, 0x13, 0xfa,
	0x15, 0xae, 0xe9, 0xef, 0xf6, 0xd3, 0x79, 0x22, 0xf7, 0xd3, 0xe4, 0x24, 0x92, 0x51, 0x9a, 0xf0,
	0x98, 0xec, 0x19, 0xc4, 0x37, 0xa7, 0x53, 0x83, 0x84, 0x56, 0x48, 0x08, 0x97, 0x9e, 0xce, 0xa3,
	0xf8, 0x24, 0x4a, 0xbe, 0x28, 0xc8, 0x16, 0x5b, 0xcc, 0xf3, 0x5e, 0x87, 0x71, 0x9a, 0xce, 0x02,
	0x57, 0x15, 0xf4, 0x84, 0xfe, 0x71, 0x60, 0x0b, 0x35, 0x63, 0x22, 0x9b, 0xa6, 0x49, 0x26, 0xc8,
	0x5d, 0x68, 0x32, 0x91, 0xcd, 0x63, 0xa9, 0xba, 0x6c, 0x0e, 0xb6, 0xfa, 0xf9, 0xd9, 0xfa, 0xe3,
	0xa9, 0x98, 0x71, 0x29, 0x74, 0x89, 0x15, 0x5b, 0x48, 0x07, 0xdc, 0x97, 0x99, 0xe9, 0x98, 0x0f,
	0x4b, 0x44, 0xdd, 0xb5, 0x44, 0xbd, 0x3a, 0xa2, 0x3e, 0x22, 0x4a, 0x6e, 0x81, 0x37, 0xe4, 0x92,
	0x07, 0xcd, 0xae, 0xdb, 0xdb, 0x18, 0x74, 0x34, 0x9d, 0xa5, 0xbc, 0x4c, 0x55, 0xe9, 0x7b, 0xb8,
	0x8e, 0x4e, 0x93, 0x61, 0xed, 0x1e, 0x43, 0x1b, 0x4d, 0xb3, 0xc0, 0x51, 0x40, 0x3b, 0x18, 0xa8,
	0xac, 0x37, 0xb3, 0xbe, 0xa0, 0x47, 0xb0, 0x8d, 0xc1, 0x17, 0x5a, 0xdd, 0x03, 0x3f, 0x6f, 0x6e,
	0x20, 0x6f, 0x54, 0x20, 0xcd, 0x4e, 0xa6, 0xf7, 0xd1, 0x67, 0xc6, 0x60, 0xe5, 0x37, 0x26, 0x89,
	0x75, 0x71, 0xea, 0x74, 0x69, 0x60, 0x03, 0x7f, 0x2f, 0x0c, 0x54, 0x60, 0xe7, 0x65, 0x20, 0x26,
	0xe2, 0xd6, 0x11, 0xf1, 0x56, 0x19, 0xe4, 0x9f, 0xcd, 0x20, 0xc5, 0xf6, 0x7f, 0x0d, 0x2a, 0xeb,
	0x55, 0x67, 0x90, 0x06, 0x3f, 0x93, 0x41, 0x96, 0x6a, 0xc6, 0xa0, 0x9f, 0xd0, 0xd6, 0xd5, 0xa1,
	0x90, 0x3c, 0x8a, 0x95, 0x3e, 0xfc, 0x87, 0x52, 0xd2, 0x67, 0xf9, 0x50, 0xad, 0x44, 0x49, 0x91,
	0xdb, 0x7c, 0x98, 0xe7, 0xfb, 0x38, 0x89, 0x64, 0xa1, 0x96, 0x1a, 0x2f, 0xf3, 0xed, 0xa1, 0x7c,
	0x97, 0xc2, 0xe1, 0x97, 0xc3, 0x41, 0x1f, 0x19, 0x8d, 0x74, 0x77, 0xac, 0xd1, 0x0e, 0xb4, 0x74,
	0xe9, 0xe0, 0x78, 0x54, 0x5c, 0x90, 0xe5, 0x02, 0xfd, 0xe5, 0x18, 0x01, 0xf4, 0x97, 0xe7, 0x75,
	0x19, 0xac, 0xae, 0x6e, 0xa9, 0x2b, 0xb9, 0x5d, 0x18, 0xef, 0x29, 0x71, 0x09, 0x16, 0xb7, 0xa0,
	0xa1, 0xad, 0xff, 0x00, 0x01, 0x5e, 0xb5, 0xbc, 0x7f, 0xb2, 0xd2, 0xfb, 0xdd, 0x2a, 0x56, 0xbd,
	0xf9, 0x23, 0xb8, 0x6a, 0xc1, 0x2f, 0x0e, 0x7f, 0xdf, 0x76, 0x3f, 0x5c, 0x41, 0xd0, 0xb6, 0xff,
	0x0e, 0x85, 0xcb, 0x96, 0x34, 0xa4, 0x09, 0x8d, 0xf1, 0xf3, 0xce, 0x05, 0xd2, 0x02, 0xff, 0x90,
	0xcf, 0x63, 0xd9, 0x71, 0x06, 0x7f, 0x5d, 0x68, 0xbf, 0xcb, 0xdf, 0xfe, 0xd7, 0x62, 0x96, 0x23,
	0x91, 0x11, 0x6c, 0x1e, 0x09, 0x89, 0x52, 0x4f, 0xd6, 0xbe, 0x2d, 0x61, 0xfd, 0x33, 0x41, 0x5e,
	0xc0, 0x15, 0x1b, 0x2a, 0x23, 0xbb, 0x95, 0xdd, 0x58, 0xbf, 0x30, 0xac, 0x96, 0x17, 0x68, 0x98,
	0x98, 0xbe, 0x80, 0x6b, 0x33, 0x15, 0xd6, 0xc7, 0xc3, 0x22, 0xa6, 0x33, 0x66, 0x13, 0xab, 0x84,
	0xda, 0x26, 0x56, 0x8a, 0x25, 0x46, 0x2b, 0x82, 0xb6, 0xde, 0xf1, 0x70, 0x8d, 0x77, 0x64, 0x0c,
	0x9d, 0x12, 0x5a, 0x46, 0xf6, 0xaa, 0xfb, 0x2d, 0x76, 0x37, 0x57, 0xd4, 0x0d, 0xe0, 0xc7, 0xa6,
	0xfa, 0xa9, 0x3f, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x82, 0x16, 0x18, 0xae, 0xe3, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WaterServiceClient is the client API for WaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WaterServiceClient interface {
	GetDeviceCount(ctx context.Context, in *DeviceCountConditional, opts ...grpc.CallOption) (*DeviceCountResponse, error)
	GetDeviceCounts(ctx context.Context, in *DeviceCountsConditional, opts ...grpc.CallOption) (*DeviceCountsResponse, error)
	GetDeviceValue(ctx context.Context, in *DeviceValueConditional, opts ...grpc.CallOption) (*DeviceValueResponse, error)
	GetDeviceValues(ctx context.Context, in *DeviceValuesConditional, opts ...grpc.CallOption) (*DeviceValuesResponse, error)
	GetDeviceDetail(ctx context.Context, in *DeviceDetailConditional, opts ...grpc.CallOption) (*DeviceDetailResponse, error)
	GetDeviceDetails(ctx context.Context, in *DeviceDetailsConditional, opts ...grpc.CallOption) (*DeviceDetailsResponse, error)
}

type waterServiceClient struct {
	cc *grpc.ClientConn
}

func NewWaterServiceClient(cc *grpc.ClientConn) WaterServiceClient {
	return &waterServiceClient{cc}
}

func (c *waterServiceClient) GetDeviceCount(ctx context.Context, in *DeviceCountConditional, opts ...grpc.CallOption) (*DeviceCountResponse, error) {
	out := new(DeviceCountResponse)
	err := c.cc.Invoke(ctx, "/main.WaterService/GetDeviceCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) GetDeviceCounts(ctx context.Context, in *DeviceCountsConditional, opts ...grpc.CallOption) (*DeviceCountsResponse, error) {
	out := new(DeviceCountsResponse)
	err := c.cc.Invoke(ctx, "/main.WaterService/GetDeviceCounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) GetDeviceValue(ctx context.Context, in *DeviceValueConditional, opts ...grpc.CallOption) (*DeviceValueResponse, error) {
	out := new(DeviceValueResponse)
	err := c.cc.Invoke(ctx, "/main.WaterService/GetDeviceValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) GetDeviceValues(ctx context.Context, in *DeviceValuesConditional, opts ...grpc.CallOption) (*DeviceValuesResponse, error) {
	out := new(DeviceValuesResponse)
	err := c.cc.Invoke(ctx, "/main.WaterService/GetDeviceValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) GetDeviceDetail(ctx context.Context, in *DeviceDetailConditional, opts ...grpc.CallOption) (*DeviceDetailResponse, error) {
	out := new(DeviceDetailResponse)
	err := c.cc.Invoke(ctx, "/main.WaterService/GetDeviceDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) GetDeviceDetails(ctx context.Context, in *DeviceDetailsConditional, opts ...grpc.CallOption) (*DeviceDetailsResponse, error) {
	out := new(DeviceDetailsResponse)
	err := c.cc.Invoke(ctx, "/main.WaterService/GetDeviceDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaterServiceServer is the server API for WaterService service.
type WaterServiceServer interface {
	GetDeviceCount(context.Context, *DeviceCountConditional) (*DeviceCountResponse, error)
	GetDeviceCounts(context.Context, *DeviceCountsConditional) (*DeviceCountsResponse, error)
	GetDeviceValue(context.Context, *DeviceValueConditional) (*DeviceValueResponse, error)
	GetDeviceValues(context.Context, *DeviceValuesConditional) (*DeviceValuesResponse, error)
	GetDeviceDetail(context.Context, *DeviceDetailConditional) (*DeviceDetailResponse, error)
	GetDeviceDetails(context.Context, *DeviceDetailsConditional) (*DeviceDetailsResponse, error)
}

func RegisterWaterServiceServer(s *grpc.Server, srv WaterServiceServer) {
	s.RegisterService(&_WaterService_serviceDesc, srv)
}

func _WaterService_GetDeviceCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCountConditional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetDeviceCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.WaterService/GetDeviceCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetDeviceCount(ctx, req.(*DeviceCountConditional))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_GetDeviceCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCountsConditional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetDeviceCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.WaterService/GetDeviceCounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetDeviceCounts(ctx, req.(*DeviceCountsConditional))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_GetDeviceValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceValueConditional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetDeviceValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.WaterService/GetDeviceValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetDeviceValue(ctx, req.(*DeviceValueConditional))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_GetDeviceValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceValuesConditional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetDeviceValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.WaterService/GetDeviceValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetDeviceValues(ctx, req.(*DeviceValuesConditional))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_GetDeviceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceDetailConditional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetDeviceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.WaterService/GetDeviceDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetDeviceDetail(ctx, req.(*DeviceDetailConditional))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_GetDeviceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceDetailsConditional)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetDeviceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.WaterService/GetDeviceDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetDeviceDetails(ctx, req.(*DeviceDetailsConditional))
	}
	return interceptor(ctx, in, info, handler)
}

var _WaterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.WaterService",
	HandlerType: (*WaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceCount",
			Handler:    _WaterService_GetDeviceCount_Handler,
		},
		{
			MethodName: "GetDeviceCounts",
			Handler:    _WaterService_GetDeviceCounts_Handler,
		},
		{
			MethodName: "GetDeviceValue",
			Handler:    _WaterService_GetDeviceValue_Handler,
		},
		{
			MethodName: "GetDeviceValues",
			Handler:    _WaterService_GetDeviceValues_Handler,
		},
		{
			MethodName: "GetDeviceDetail",
			Handler:    _WaterService_GetDeviceDetail_Handler,
		},
		{
			MethodName: "GetDeviceDetails",
			Handler:    _WaterService_GetDeviceDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "water.proto",
}
